spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/zedb
    username: zedabodega
    password: zedabodega123
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
